### ISSUE TITLE
div input-group

### ISSUE THREAD

**Issue by jddev14** [FuKe/angular2-number-picker#1]
the div where you set the class input-group
...is it possible that you can change that in your repository to a span?

because im trying to use your repository and i find it pretty helpfull ,, but i cant use bootstrap..

**Comment by FuKe** [comment]
Hi Jonathan
Sorry about the late answer. I'll look into it in the upcoming week (most possibly Tuesday), but I think it should be possible :)

**Comment by FuKe** [comment]
Hi Jonathan
I've changed the input-group to span instead of div.
The new version number is 0.8.7 :)
