### ISSUE TITLE
having some issue importing  the angular2-number picker 

### ISSUE THREAD

**Issue by maxto024** [FuKe/angular2-number-picker#2]
I am using  angular 2 cli  with materialize  and then i see  angular 2-number-picker is using  bootstrap then i install bootstrap 
![screenshot from 2017-02-12 00-15-01](https://cloud.githubusercontent.com/assets/17172422/22856270/55d3d52e-f0b8-11e6-9f0c-f5e60330a5b4.png)

I get this error 
![screenshot from 2017-02-12 00-00-14](https://cloud.githubusercontent.com/assets/17172422/22856284/754d557e-f0b8-11e6-9b46-5c5e4963f755.png)

I import like this
![screenshot from 2017-02-12 00-10-45](https://cloud.githubusercontent.com/assets/17172422/22856280/6bccb92c-f0b8-11e6-8333-ea0d5d34a15d.png)

**Comment by FuKe** [comment]
Hi Max. 
Have you imported "@angular/forms"?

**Comment by FuKe** [comment]
Oh, I can see you've imported Angular forms. Have you imported Angular forms to the module using the number picker component? :)

**Comment by maxto024** [comment]
yes I imported but the  before i even use   I just imported in app.module then i get that error

**Comment by maxto024** [comment]
please still i have that error one ever i try to  put  declaration in NumberPickerComponent  As i told you i am using angular 2 cli  please did you get any solution

**Comment by FuKe** [comment]
Hi Mohammed,
sorry for the late answer.

I've managed to reproduce your error, by creating a new project and importing the NumberPickerComponent into the project.
What you need to do to make it work, is to import "ReactiveFormsModule" into your module as well, from "@angular/forms" :)
